sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t nkdocker/docker-react-example .

script:
  - docker run -e CI=true nkdocker/docker-react-example npm run test
